version: 0.0.{build}
image: WMF 5
install:
  - ps: choco install pester --pre
build: off
test_script:
  - ps: Import-Module "C:\projects\posh-cats\posh-cats.psm1"
  - ps: |
        $testResultsFile = ".\tests\TestsResults.xml"
        $res = Invoke-Pester -OutputFormat NUnitXml -OutputFile $testResultsFile -PassThru -EnableExit
        (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path $testResultsFile))
        if ($res.FailedCount -gt 0) { throw "Tests failed." };
deploy_script:
- ps: echo "deploy"
